version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  bookkeeper:
    image: apache/bookkeeper:4.13.0
    environment:
      BK_zkServers: zookeeper:2181
    ports:
      - "3181:3181"
      - "8080:8080"

  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"

